[package]
name = "mimerrust-example"
version = "1.0.1"
edition = "2021"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mimerrust = "1.0.3"
